# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.IntegerField(default=0, verbose_name='是否激活'),
        ),
    ]
