# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 17:01
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('a_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='小说id')),
                ('a_authorname', models.CharField(max_length=20, verbose_name='小说作者')),
                ('a_title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('a_info', models.CharField(max_length=500, verbose_name='文章描述')),
                ('a_content', DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='文章内容')),
                ('a_img', models.CharField(max_length=150, null=True, verbose_name='封面')),
                ('a_createtime', models.DateTimeField(db_index=True, default=datetime.datetime.now, null=True, verbose_name='添加时间')),
                ('a_price', models.IntegerField(default=0, null=True, verbose_name='单价')),
                ('a_flag', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, null=True, verbose_name='控制字段')),
                ('operator', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='api操作者')),
            ],
            options={
                'verbose_name': '小说',
                'verbose_name_plural': '小说',
                'db_table': 'art',
                'ordering': ['-a_createtime'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='章节标题')),
                ('content', models.CharField(max_length=300, verbose_name='章节url')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='添加时间')),
                ('a_id', models.ForeignKey(db_column='a_id', on_delete=django.db.models.deletion.CASCADE, to='books.Art', verbose_name='小说')),
            ],
            options={
                'verbose_name': '小说章节',
                'verbose_name_plural': '小说章节',
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('t_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='标签id')),
                ('t_name', models.CharField(max_length=20, verbose_name='文章标签')),
                ('t_info', models.CharField(default='小说', max_length=50, null=True, verbose_name='标签描述')),
                ('t_createtime', models.DateTimeField(db_index=True, default=datetime.datetime.now, null=True, verbose_name='创建时间')),
                ('t_flag', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, null=True, verbose_name='控制字段')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tag',
                'ordering': ['-t_createtime'],
            },
        ),
        migrations.AddField(
            model_name='art',
            name='t_id',
            field=models.ForeignKey(db_column='t_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='books.Tag', verbose_name='关联文章标签'),
        ),
    ]
