# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20181107_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='operator',
        ),
    ]
